minApprovals:
  MEMBER: 0
  COLLABORATOR: 0

maxRequestedChanges:
  COLLABORATOR: 0

updateBranch: true
deleteBranchAfterMerge: true
mergeMethod: squash

requiredLabels:
- automerge

blockingTitleRegex: '\bwip\b'

reportStatus: true
