language: python
install:
  - if [ ! -f "$HOME/env/done" ]; then sh tests/setup.sh; fi
  - source "$HOME/env/miniconda/etc/profile.d/conda.sh"
  - conda activate ile-de-france
  - export PATH=$HOME/env/jdk8u252-b09/bin:$PATH
  - export PATH=$HOME/env/apache-maven-3.6.3/bin:$PATH
  - export PATH=$HOME/env/osmosis/bin:$PATH

script:
  - java -version
  - mvn -version
  - osmosis -v
  - pytest tests/

cache:
  directories:
    - $HOME/.m2
    - env
