## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: C:/Users/arthur.burianne/Documents/dev_simulations/emc2_tmp

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the output population in the output_path (see below)
  #- documentation.paper # to create plots
  #- matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 8

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: emc2

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.1
  random_seed: 1234
  acquisition_sample_size: 1
  home_location_sampling: weighted
  departments: ["33"]
  regions: []
  mode_choice: true
  output_prefix: emc2_

  # Paths to the input data and where the output should be stored
  data_path: C:/Users/arthur.burianne/Documents/sources_data/bordeaux_data
  output_path: C:/Users/arthur.burianne/Documents/dev_simulations/emc2_output
  
  # Data exceptions
  population_year: 19


  # Only interesting if you run the simulation
  java_memory: 14G

  # Uncommented below to enable vehicle fleet generation
  # generate_vehicles_file: True
  # generate_vehicles_method: fleet_sample
  # vehicles_data_year: 2015
