## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /path/tp/my/cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the output population in the output_path (see below)
  #- matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)

# Here the configuraiton of the pipeline starts
config:

  ##############################
  # Some general configuration #
  ##############################

  ## Number of CPUs to use
  processes: 4

  ################
  # Random seeds #
  ################

  ## global random seed for the output population
  random_seed: 1234

  ## bpe specific random seed when impute missing coordinates for known IRIS
  # bpe_random_seed: 0

  ##################################################
  # Define sampling rate for the output population #
  ##################################################

  sampling_rate: 0.001

  #################################
  # household travel survey (HTS) #
  #################################

  ## Define whether to use ENTD or EGT as the HTS
  hts: entd # entd, egt, edgt_lyon, edgt_44, mobisurvstd

  ## Whether to filter people going outside of the area and other filters
  # filter_hts: true

  ## Activity purposes included in the generated activities.
  ## Purposes not present in the list below is put in the "other" category.
  # activity_purposes: ["leisure", "shop"]

  ## if selected, chose the source for edgt_lyon
  # edgt_lyon_source: unchosen # unchosen, adisp, cerema

  ## path to the zipfile / directory where the HTS to be read by MobiSurvStd is located
  ## path is relative to `data_path`
  # mobisurvstd:
  #   path: my_survey.zip

  ##################
  # Zone selection #
  ##################

  ## select regions by region_id
  # regions: [11]

  ## select departments by department_id
  # departments: []

  #######################
  #     Output paths    #
  #######################

  ## output folder
  output_path: /path/to/my/output

  ## output prefix, appended to file names
  # output_prefix: ile_de_france_

  ## file formats that should be exported
  # output_formats: ["csv", "gpkg"] # ["csv", "gpkg", "parquet", "geoparquet"]

  ## whether to write location id informations
  # output_location_ids: false

  ##############################
  #  Algorithms configurations #
  ##############################

  ## Use the bhepop2 package for attributing income
  # income_assignation_method: bhepop2 # uniform, bhepop2

  ## Activate if you want to run mode choice, will assign a mode to output trips
  mode_choice: true

  ## Census data
  # It is possible to pipe raw per-person or per-household data from the census to the generated persons:

  # census_attributes:
  # - name: household_type
  #   raw: MODV
  #   scope: household # optional: by default attributes are added to persons, but you can choose households
  # - name: rooms
  #   raw: NBPI

  ## Statistical matching configuration

  ## Minimum number of observation to sample from
  # matching_minimum_observations: 20

  ## Persons whose age is below this value are not matched to hts persons.
  ## In most hts, persons below 5 are not surveyed for their trips so they would end up being
  ## matched to older persons.
  ## See https://github.com/eqasim-org/eqasim-france/issues/383
  ## Recommended values:
  ## - 5: persons below 5 are generated but have no trip and no enriched attributes
  ## - 0: persons below 5 have trips and enriched attributed corresponding to those of a persons
  #    between 5 and 14
  ## - 16: for EMG 2023 (which only survey persons over 16), persons below 16 are generated but have
  #    no trip and no enriched attributes
  # matching_minimum_age: 5

  ## list of attributes to use for matching
  # matching_attributes: ["sex", "any_cars", "age_class", "socioprofessional_class", "departement_id"]

  ## Match based on professional occupation
  # matching_attributes: ["detailed_professional_occupation", "*default*"]

  ## Use INSEE's urban type in statistical matching
  # use_urban_type: true
  # urban_type_path: urban_type/UU2020_au_01-01-2023.zip
  # matching_attributes: ["urban_type", "*default*"]

  ## list of attributes to enrich the persons from hts data
  ## this only work with hts: mobisurvstd
  ## the list of possible keys can be found here: https://mobisurvstd.github.io/MobiSurvStd/format/persons.html
  # extra_enriched_attributes:
    # - "detailed_education_level"
    # - "work_only_at_home"

  ## Exclude entreprise without any employee (trancheEffectifsEtablissement is NA, "NN" or "00")
  # exclude_no_employee: true

  ## source for the education locations
  # education_location_source: bpe # bpe, addresses

  ## max iterations for the secondary location selection algorithm
  # secondary_activities:
  #   maximum_iterations: .inf
  #   chain_solver: default

  # Locations for escort activities are drawn from the activity types below, with the given weights.
  # By default, there is a 71% probability that a escort activity is drawn from "education" locations.
  # The default weights were derived from observed escort activities in an aggregation of travel surveys.
  # Possible activity types: "education", "shop", "leisure", "task", "transport", "other".
  # escort_locations_activities: ["education", "leisure", "task", "transport", "shop"]
  # escort_locations_weights: [0.71, 0.16, 0.07, 0.05, 0.01]

  ## Buffer arround buildings to capture adresses in their vicinity
  # home_address_buffer: 5.0

  ## How sample homes, using weights or not
  # home_location_weight: housing # "uniform", "housing"

  # home_location_source: addresses # "addresses", "buildings", "tiles"

  ## When running matsim

  ## performing one run of the matsim simulation or not
  # run_matsim: true

  ## creating the far or not
  # write_jar: true

  ## Cutter settings: Used to define a specific area for analysis or simulation
  # cutter:

    ## Path to the directory containing the cutter geojson file
    # path: cutter

    ## Name of the cutter file (e.g., GeoJSON file defining the area)
    # file: cutter.geojson

    ## Name of the cutter (used for output file naming)
    # name: paris

    ## Whether to apply the cutter after the full simulation (True/False)
    # after_full_simulation: True

  ## NoiseModelling settings: Configuration for noise exposure or noise map generation
  # noise:

    ## Type of noise computation to perform ("exposure" for exposure analysis, "maps" for noise maps)
    # compute: exposure

    ## Size of the time bins for noise computation, in seconds (e.g., 3600 for hourly bins)
    # time_bin_size: 3600

    ## Start time for noise computation, in seconds (e.g., 0 for midnight)
    # time_bin_min: 0

    ## End time for noise computation, in seconds (e.g., 86400 for 24 hours)
    # time_bin_max: 86400

    ## Maximum order of reflections to consider (e.g., 1 for first-order reflections)
    # refl_order: 1

    ## Maximum distance for considering noise sources, in meters
    # max_src_dist: 750

    ## Maximum distance for considering reflections, in meters
    # max_refl_dist: 50

  ############################
  #  Analysis configuration  #
  ############################

  ## Whether to use previously generated files or not
  # analysis_from_file: false

  ## prefix of the files to compare to
  # comparison_file_prefix: other_

  ##########################
  #  Tools configuration   #
  ##########################

  ## Mostly interesting if you run the simulation, or you activate the `mode_choice` option,

  ## Binaries paths
  # git_binary: git
  # java_binary: java
  # maven_binary: mvn
  # maven_local_cache: false

  ## Binaries parameters
  # java_memory: 14G
  # maven_skip_tests: false

  ## eqasim-java parameters
  # eqasim_version: 1.5.0
  # eqasim_branch: develop
  # eqasim_commit: ece4932
  # eqasim_repository: https://github.com/eqasim-org/eqasim-java.git
  # eqasim_path: ""
  # eqasim_tag:


  ## pt2matsim parameters
  # pt2matsim_version: 22.3
  # pt2matsim_branch: v22.3

  ## Strategy to use in pt2matsim gtfs processing
  # gtfs_date: dayWithMostServices

  ## Export the detailed geometry of the network before simplification in pt2matsim
  # export_detailed_network: true

  #################
  #  Input paths  #
  #################

  ## Absolute root path of all input data
  data_path: /path/to/my/data

  # census_path: rp_2019/RP2019_INDCVI_csv.zip
  # census_csv: FD_INDCVI_2019.csv

  # ban_path: ban_idf

  # bdtopo_path: bdtopo_idf

  # bpe_path: bpe_2021/bpe21_ensemble_xy_csv.zip
  # bpe_csv: bpe21_ensemble_xy.csv

  # gtfs_path: gtfs_idf

  # income_com_path: filosofi_2019/indic-struct-distrib-revenu-2019-COMMUNES.zip
  # income_com_xlsx: FILO2019_DISP_COM.xlsx
  # income_reg_path: filosofi_2019/indic-struct-distrib-revenu-2019-SUPRA.zip
  # income_reg_xlsx: FILO2019_DISP_REG.xlsx
  # income_year: 19

  # tiles_path: tiles_2019/Filosofi2019_carreaux_200m_gpkg.zip
  # tiles_file: carreaux_200m_met.gpkg

  # od_pro_path: rp_2019/RP2019_MOBPRO_csv.zip
  # od_sco_path: rp_2019/RP2019_MOBSCO_csv.zip
  # od_pro_csv: FD_MOBPRO_2019.csv
  # od_sco_csv: FD_MOBSCO_2019.csv

  ## external education locations file
  # education_file: education/education_addresses.geojson

  # osm_path: osm_idf

  # siren_path: sirene/StockUniteLegale_utf8.zip
  # siret_path: sirene/StockEtablissement_utf8.zip
  # siret_geo_path: sirene/GeolocalisationEtablissement_Sirene_pour_etudes_statistiques_utf8.zip

  # iris_path: iris_2021

  # population_path: rp_2019/base-ic-evol-struct-pop-2019.zip
  # population_xlsx: base-ic-evol-struct-pop-2019.xlsx
  # population_year: 19

  ## population projections
  # projection_path: projection_2021
  # projection_scenario: 00_central
  # projection_year: 2030

  # vehicles_method: default # fleet_sample, default
  # critair_path: critair
  # 2rm_path: vehicles
  # vehicles_year: 2021
  # with_motorcycles: false
