name: Deploy documentation

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
            python-version: '3.13' 

      - name: Set up dependencies
        run: pip install -r docs/requirements.txt

      - name: Build the documentation
        run: cd docs && make html

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_build/html
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
